# Generated by Django 4.2 on 2024-03-12 18:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название привычки')),
                ('place_of_execution', models.CharField(max_length=255, verbose_name='Место выполнения')),
                ('time_execution', models.TimeField(verbose_name='Время начала выполнения привычки')),
                ('action', models.TextField(verbose_name='Действие')),
                ('is_pleasant_habit', models.BooleanField(blank=True, default=False, verbose_name='Признак приятной привычки')),
                ('periodicity', models.PositiveSmallIntegerField(default=1, verbose_name='Периодичность')),
                ('award', models.TextField(blank=True, null=True, verbose_name='Вознаграждение')),
                ('time_to_complete', models.DurationField(blank=True, default=datetime.timedelta(seconds=120), verbose_name='Время на выполнение')),
                ('is_publish', models.BooleanField(default=False, verbose_name='Признак публичности')),
                ('accompanying_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='Связанная привычка')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
